<?php

if (!defined('_PS_VERSION_'))
    exit;

class pwspecialspageAkciiModuleFrontController extends ModuleFrontController
{
    public $module;

    public function initContent()
    {
        $xml = @simplexml_load_file(_PS_MODULE_DIR_ .'pwspecialspage/data.xml');
        $arr = array();
        if (!empty($xml)) {
            foreach ($xml->link as $key => $value) {
				if(isset($value->img)) $value->image_date = filemtime(_PS_MODULE_DIR_.$this->module->name.'/'.$value->img);
                $arr[] = $value;
            }
        }

        $this->context->smarty->assign(
            array(
                'data_links' => $arr,
            )
        );

        parent::initContent(); // TODO: Change the autogenerated stub

        $this->setTemplate('akcii.tpl');
    }



}
